image: bradrydzewski/python:2.7-scrapinghub


script:
    - sudo custom/install-plugins.sh $$ADDITIONAL_DOWNLOADS

publish:
  docker:
    docker_host: $DOCKER_HOST
    image_name: i.scrapinghub.com/redmine/$CI_BRANCH
    keep_build: true
