#!/bin/sh

sudo apt-get install git

mkdir -p /home/redmine/data/plugins && cd /home/redmine/data/plugins

git clone https://github.com/arkhitech/redmine_mentions
git clone https://github.com/sciyoshi/redmine-slack redmine_slack
git clone https://github.com/scrapinghub/redmine_didyoumean
git clone https://github.com/peclik/clipboard_image_paste
